# -*- coding: utf-8 -*-
"""23년 코칭스터디 1주차 QUIZ

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fLyQdZHWNXT0Rs-kqe8tlPNjEy9oJyBp
"""


# # 1번 문제
# num_list=[1,5,7,15,16,22,28,29]

# def get_odd_num(num_list):
#   return 1,5,7,15,29
# print (get_odd_num(num_list))


# # 2번 문제
# sentence= "way a is there will a is there where"

# def reverse_sentence(sentence):
#   return "where there is a will there is a way"
# print (reverse_sentence(sentence))


# # 3번 문제
# score = [(100, 100), (95, 90), (55, 60), (75, 80), (70, 70)]
# def get_avg(score):
#     for i in range(len(score)):
#         print(f"{i} 번, 평균 : {sum(score[i])/len(score[i])}")
# get_avg(score)


# 4번 문제
from collections import Counter

dict_first = {'사과': 30, '배': 15, '감': 10, '포도': 10}
dict_second = {'사과': 5, '감': 25, '배': 15, '귤': 25}

def merge_dic(dic_first, dict_second):   
    m_counter = dict(Counter(dict_first) + Counter(dict_second))   
    sort_m =dict (sorted(m_counter.items(), key= lambda x: x[0]))
    print(sort_m)

merge_dic(dict_first, dict_second)

